
# install internal upcload repository
#
# based on https://github.com/malk/ansible-java8-oracle/blob/master/tasks/main.yml
#
# run:
# ansible-playbook "yourplaybook.yaml" -i ./hosts
#
- name: Add group "serposcope"
  group: name=serposcope

- name: Add user "serposcope"
  user: name=serposcope group=serposcope home=/var/www/serposcope/

- name: Install dependencies
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - software-properties-common
    - dirmngr
    - default-jre
    - default-jdk

- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository:
    repo: deb ppa:webupd8team/java xenial main
    state: present

- name: Add an apt key by id from a keyserver
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EEA14886

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: update cache and ignore errors in case of problems
  become: yes
  apt: update_cache=yes
  ignore_errors: yes

- name: purge java 8 installer - to avoid problems if installation is repeated
  become: yes
  apt:
    name: oracle-java8-installer
    purge: yes
    state: absent

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - ca-certificates

- name: create serposcope owner directory
  file: path=/var/www/serposcope
        state=directory
        owner=serposcope
        group=serposcope
        mode=0774

- name: Download serposcope files
  get_url:
    url: https://serposcope.serphacker.com/download/2.10.0/serposcope_2.10.0_all.deb
    dest: /var/www/serposcope

- name: exec serposcope
  shell: dpkg -i serposcope_2.10.0_all.deb
  args:
    chdir: /var/www/serposcope
