
# install internal upcload repository
#
# based on https://github.com/malk/ansible-java8-oracle/blob/master/tasks/main.yml
#
# run:
# ansible-playbook "yourplaybook.yaml" -i ./hosts
#
- name: Add group "serposcope"
  group: name=serposcope

- name: Add user "serposcope"
  user: name=serposcope group=serposcope home=/var/www/serposcope/

- name: update cache and ignore errors in case of problems
  become: yes
  apt: update_cache=yes
  ignore_errors: yes

- name: Install dependencies
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - java-common
    - dirmngr
    - default-jre
    - default-jdk

- name: Download serposcope files
  get_url:
    url: https://d3pxv6yz143wms.cloudfront.net/8.212.04.1/java-1.8.0-amazon-corretto-jdk_8.212.04-1_amd64.deb
    dest: /var/www/serposcope

- name: exec serposcope
  shell: dpkg --install java-1.8.0-amazon-corretto-jdk_8.212.04-1_amd64.deb
  args:
    chdir: /var/www/serposcope

- name: create serposcope owner directory
  file: path=/var/www/serposcope
        state=directory
        owner=serposcope
        group=serposcope
        mode=0774

- name: systemctl location config file directory
  file: path=/etc/systemd/system/serposcope.service.d state=directory owner=root group=root mode=0755

- name: Copy nginx configuration for WordPress
  template: src=systemctl-override.conf dest=/etc/systemd/system/serposcope.service.d/override.conf

- name: Download serposcope files
  get_url:
    url: https://serposcope.serphacker.com/download/2.10.0/serposcope_2.10.0_all.deb
    dest: /var/www/serposcope

- name: exec serposcope
  shell: dpkg -i serposcope_2.10.0_all.deb
  args:
    chdir: /var/www/serposcope
